POSTGRES_VENDOR: "postgresql" 
POSTGRES_VERSION: 14 
DATA_DIR_NAME: "data" 
PG_LOG_DIR: "/var/log/pg_log_dir" 
DBMS_ROOT_DIRECTORY: "/pgdata_dir" 
POSTGRES_PORT: 5432 
MAX_CONNECTION: 110 
USER_TECHNICAL: "user_technical"
SAVE_LIST_PASSWORDS: false 
PG_CUSTOM_OPT: true 
VIRTUAL_IP:  "192.168.0.5"
USER_REPLICA: "user_replica"
TIME_OUT: 180 
TIMEOUT_COROSYNC: 4000 
DISK_DEVICE_DBMS: "" 
SIZE_DBMS_IN_PROCENT:  100
VG_NAME_DBMS: "vg_pgdata" 
LV_NAME_DBMS: "lv_pgdata" 
PG_BACKUP: false
USER_BACKUP: "user_backup"
DBMS_BACKUP_DIRECTORY: "/backups_dir"
CRON_BACK_HOUR: "22"
CRON_BACK_MIN: "00"
DISK_DEVICE_BACKUP: "" 
SIZE_BACKUP_IN_PROCENT: 100 
VG_NAME_BACKUP: "vg_pgbackup" 
LV_NAME_BACKUP: "lv_pgbackup" 
PG_PROFILE: false 
CRON_PROFILE_HOUR: "*"
CRON_PROFILE_MIN: "*/20"
NAME_PG_PROFILE: "pg_profile--4.2.tar.gz" 
PG_AUDIT: false


