---
- block:

  - name: Create directory backup
    file: 
      path: "{{ item }}"
      state: directory
    with_items:
        - "{{ DBMS_BACKUP_DIRECTORY }}"
        - "{{ DBMS_BACKUP_DIRECTORY }}/archive"
        - "{{ DBMS_BACKUP_DIRECTORY }}/archive_xlog"

  - name: Change owner postgres directory backups
    file: 
      path: "{{ DBMS_BACKUP_DIRECTORY }}"
      state: directory
      owner: postgres
      group: postgres
      recurse: yes

  - name: Install bc
    yum: 
      name: "bc"
      state: present

  - name: Copy script backupPG.sh
    template:
      src: "backupPG.sh.j2"
      dest: "{{ postgres_home_dir }}/backupPG.sh"
      owner: postgres
      group: postgres
      mode: 0700
  
  - name: Install Batchjobs on crontab
    cron:
      name: "Job start PostgreSQL backup"
      minute: "0"
      hour: "22"
      job: "{{ postgres_home_dir }}/backupPG.sh"
      disabled: "no"
      user: "postgres"
    tags:
     - cronjobs
  
  - name: Start backup DBMS
    shell: "sudo -u postgres {{ postgres_home_dir }}/backupPG.sh"   
  
  when: (('master_server' in groups and groups['master_server']) and (inventory_hostname in groups['master_server'])) or (('slave_servers' in groups and groups['slave_servers']) and (inventory_hostname in groups['slave_servers']))